=== mfmstr/OPPA-XML-JSON-Task/XML Structure/employees.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="LastName" type="xs:string"/>
                            <xs:element name="Gender">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Male"/>
                                        <xs:enumeration value="Female"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Phone">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="City">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Tbilisi"/>
                                        <xs:enumeration value="Batumi"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Departament">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="IT"/>
                                        <xs:enumeration value="HR"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ID" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== mfmstr/OPPA-XML-JSON-Task/XML Structure/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
    <employee ID="1">
        <Name>Giorgi</Name>
        <LastName>Kharebava</LastName>
        <Gender>Male</Gender>
        <Phone>551172230</Phone>
        <City>Tbilisi</City>
        <Departament>IT</Departament>
    </employee>
    <employee ID="2">
        <Name>Ana</Name>
        <LastName>Maisuradze</LastName>
        <Gender>Female</Gender>
        <Phone>599999999</Phone>
        <City>Batumi</City>
        <Departament>HR</Departament>
    </employee>
</employees>
